### ISSUE TITLE
Can this move data from S3 -> Azure? 

### ISSUE THREAD

**Issue by zfrenchee** [Azure/blobxfer#10]

**Comment by alfpark** [comment]
@zfrenchee You need a tool to download data from S3 to your local machine first. Then you can use this tool to upload the downloaded data to Azure.

**Comment by alfpark** [comment]
Closing since no response given.

**Comment by zfrenchee** [comment]
Sorry @alfpark. That likely won't work because our data is too large to download to a local machine first. (50TB) No worries though.
