### ISSUE TITLE
Support a delete only option (disables transfer)

### ISSUE THREAD

**Issue by PascalSl** [Azure/blobxfer#101]
#### Feature Request Description
When using synccopy, there is the ability to delete extraneous files, but this only works in conjunction with syncing the files. There is no option to say that syncing is not necessary, but deletion is.

The usecase is this: we have an azure storage container which we use as our source. However, there are some files on the source that are deliberately not pushed to the destinations. We don't want the additional files to appear on the sources.
Then again, when a file is not on the source, we are sure we don't want it on the destination. That's why we are looking for a flag that disables syncing, while allowing deletion.

Can you keep us up to date whether this can be put on the Blobxfer roadmap somewhere or if any additional information is required?

#### Describe Preferred Solution
Be able to set a configuration parameter (ie. CLI: --disable-syncand, YAML: disable_sync ), that disables the syncing.

#### Describe Alternatives Considered
AzCopy, which doesn't do Azure to Azure comparison

**Comment by alfpark** [comment]
This option should apply to all transfer modes.

**Comment by alfpark** [comment]
This has been added in `develop`, please provide feedback if addresses your issue.

**Comment by PascalSl** [comment]
Thanks for the swift response. Can't say when I'll be able to do the check, in the meanwhile I'm assigned different tasks, but it's somewhere in my todo.
