### ISSUE TITLE
If blob folders have a shared prefix, they are all downloaded

### ISSUE THREAD

**Issue by ant0nsc** [Azure/blobxfer#106]
#### Problem Description
I'm transferring folders from Azure blob storage to a local machine. My container has files as follows:

    foo/1.txt
    foo/2.txt
    foo_bar/1.txt
    foo_bar/2.txt

I'm adding to my `AzureSourcePath` 

    source.add_path_with_storage_account("container/foo/", "mystorageaccount")

When I start the downloader, it will download all of the folders `foo` and `foo_bar`, even though I would expect only `foo` to be downloaded. And that's painful in my case, because I have 4 folders that get downloaded instead of only 1, and each has several GB of data....

#### Steps to Reproduce
Create a container with files

    foo/1.txt
    foo/2.txt
    foo_bar/1.txt
    foo_bar/2.txt

and then attempt to download only all files that have prefix `foo/`
#### Expected Results
2 files get downloaded
#### Actual Results
4 files get downloaded
#### Additonal Comments
I think the culprit is `normalize_azure_path` in `util.py`, which gets called in `add_path_with_storage_account`. Path normalization strips both leading AND trailing slashes, but a trailing slash should be retained.

**Comment by alfpark** [comment]
Closing issue, please re-open if you feel this has not been addressed.
