### ISSUE TITLE
SLES 12 SP1 - error : no module named azure.common

### ISSUE THREAD

**Issue by hermanndms** [Azure/blobxfer#11]
Hi,

I have no Python experience. Sorry. Just wanted to use blobxfer as a tool to backup some SAP data to a storage account. But whatever I tried now for the last few hours - whenever I try to call blobxfer it comes back with the error that it cannot find a module named azure.common

I am on a SLES 12 SP1 VM on Azure. I manually installed e.g. azure-servicemanagement-legacy==0.20.5 after I got also an error. I used pip to install exactly this version and then the error was gone.

But after resolving all those issues I always get stuck with this azure.common error. 

Could someone give me a hint how to solve this ?

Thanks

Regards

Hermann

**Comment by alfpark** [comment]
@hermanndms There's no need to manually install the python dependencies. Ensure you have a compiler, ssl, ffi and python development libraries and then simply issue `pip install blobxfer`.
