### ISSUE TITLE
Loosen ruaml.yaml version requirements

### ISSUE THREAD

**Issue by temporaer** [Azure/blobxfer#115]
#### Feature Request Description
- installing blobxfer along azureml-sdk results in a ruaml.yaml version conflict
- azureml requires 
    - ruamel.yaml [required: >=0.15.35,<=0.15.89, installed: 0.15.89]
- blobxfer requires:
   -   'ruamel.yaml~=0.16.5',

#### Describe Preferred Solution
investigate whether version 0.15.89 is compatible with blobxfer and if so, loosen requirements in setup.py

**Comment by temporaer** [comment]
Note: this has been fixed the "right" way in azureml-sdk now.

**Comment by sytelus** [comment]
@alfpark - this is a real issue that causes conflict with Azure SDK. Could you please fix this? Do you have any strong reason for not having similar version constraint as rest of the Azure SDK like @temporaer  pointed out?
