### ISSUE TITLE
Upgrade to azure-storage-blob 12.3.1, which has async capabilities

### ISSUE THREAD

**Issue by HansBrende** [Azure/blobxfer#120]
#### Feature Request Description
Upgrade to azure-storage-blob 12.3.1, which has an async client. I would think that you'd be able to get rid of the blocking transfer threads and do fully asynchronous transfers with this new capability. I would imagine that would come with a huge performance boost.

**Comment by alfpark** [comment]
Tracking on the other issue instead.
