### ISSUE TITLE
Rework on documentation needed?

### ISSUE THREAD

**Issue by gn4711** [Azure/blobxfer#122]
Im trying this tool first time, and using the samples described here:
https://github.com/Azure/blobxfer/blob/master/docs/10-cli-usage.md

it says:
blobxfer upload --storage-account mystorageaccount --sas "mysastoken" --remote-path mycontainer --local-path . --no-recursive --rsa-public-key ~/mypubkey.pem

I replaced the entries with my inputs for storrage account name, my sas token, and also name of mycontainer and a public pem file i created.

But i got this **exception**, where the message absolutly makes no sense to me. 
**ValueError: Specified both --storage-url and --storage-account, --mode, --endpoint, or --remote-path**

I tried variations or --storage.... parameters, but it is not working.

I would expect a clear error message regarding a missing input or something like that. General speaking: 
Samples are not working for me.

**Comment by gn4711** [comment]
I just tried the yaml example for uploading as well. same result. 
when i check the code which raises the error, i have the feeling these argument checks are not right.

**Comment by alfpark** [comment]
Please properly fill out a bug report including which version you are using. I cannot repro your error. The exception message will be clarified. That error occurs when you are using the `--storage-url` option in combination with the other "break out" options.
