### ISSUE TITLE
setup_logger leaves an open file descriptor each execution (if file is provided)

### ISSUE THREAD

**Issue by freak2100** [Azure/blobxfer#124]
I am using blobxfer to upload data to azure, and I've noticed that after many calls I start to get "Too many open files" errors.
After looking into it, each time I start an upload procedure, util.setup_logger is being called and creates a new logging.FileHandler, even though I am using the same log file each time, which cause many open file descriptors to remain open.
I fixed my code by avoiding log file (log to console only), but I think this can be considered a bug...

**Comment by freak2100** [comment]
Oops, this is in blobxfer_cli, not blobxfer

**Comment by alfpark** [comment]
Please re-open with more information, there is not enough here to understand how you are using the library. From my review, this should not happen unless you're calling `blobxfer.util.setup_logger` multiple times for the same logfile.
