### ISSUE TITLE
Trying to download with a SAS

### ISSUE THREAD

**Issue by ayang99** [Azure/blobxfer#13]
Hi, 

I'm running into problems trying to do a basic download. I generated a SAS for a specific blob in Storage Explorer and am running blobxfer 0.12.0 in a Ubuntu 14.04 VM:

blobxfer --download --remoteresource [blob_id] --saskey "https://myaccount.blob.core.windows.net/mycontainer/[blob_id]?st=2016-11-23T14%3A50%3A00Z&se=2016-11-24T14%3A50%3A00Z&sp=rl&sv=2015-12-11&sr=b&sig=[signature]" myaccount mycontainer .

but this results in:

script start time: 2016-11-23 17:36:26
generating local directory structure and pre-allocating space
Traceback (most recent call last):
  File "/usr/local/bin/blobxfer", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/blobxfer.py", line 2561, in main
    localfile, blob, False, blobdict[blob])
  File "/usr/local/lib/python2.7/dist-packages/blobxfer.py", line 1793, in generate_xferspec_download
    container_name=args.container, blob_name=remoteresource)
  File "/usr/local/lib/python2.7/dist-packages/blobxfer.py", line 1444, in azure_request
    return req(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/blobxfer.py", line 592, in get_blob_properties
    response.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. for url: https://myaccount.blob.core.windows.net/mycontainer/[blob_id]?https://myaccount.blob.core.windows.net/mycontainer/[blob_id]?st=2016-11-23T14%3A50%3A00Z&se=2016-11-24T14%3A50%3A00Z&sp=rl&sv=2015-12-11&sr=b&sig=[signature]

The URL being reported in the error certainly doesn't look like what I'm passing in (not sure if it's an artifact in the terminal window). I am able to use the supplied SAS with curl no problems.

More sample usages in the blobxfer README would be greatly appreciated!

Thanks,
Andy

**Comment by alfpark** [comment]
@ayang99 The SAS should be just the SAS token itself (?st=... or st=...).

**Comment by ayang99** [comment]
Many thanks. That worked.
