### ISSUE TITLE
Removing data after upload

### ISSUE THREAD

**Issue by robinaly** [Azure/blobxfer#130]
#### Feature Request Description
- Is your feature request related to a problem? Please describe.
- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

We are working on devices with relatively little storage. Here it would be useful to be able to remove successfully transferred files to save long syncing times and to ensure that the local storage does not overflow. One particular challenge will be that some of the files might be still actively written and hence shouldn't be unlinked. I am not sure whether this is easy to find out whether a file is open.

#### Describe Preferred Solution

I would like a move operation that is similar to sync but removes the files from local storage after being investigated. 

#### Describe Alternatives Considered

For some cases, there might be a workaround so that open files do not have to be considered. 

#### Additional Context

Nothing comes to mind. 

Thanks for building this software.

**Comment by alfpark** [comment]
Thanks for the suggestion, however, this operation would be outside of the scope of this tool. You can create a composite script that invokes blobxfer (like a full sync) and assuming success, you can follow up with deleting in your own script.
