### ISSUE TITLE
Feature Request: specify subdirectory for fileshare

### ISSUE THREAD

**Issue by BramGruneir** [Azure/blobxfer#15]
When uploading to fileshare, it would be great if I could specify a specific sub directory.
Right now, I have to create the structure locally, which is problematic.

For example, I have 5 machines in a cluster called `gamma` and I want to backup each one to the same share.

say to 
```
gamma machine0/...
gamma machine1/....
gamma machine2/...
gamma machine3/...
gamma machine4/...
```

```
blobxfer cockroachbackup gamma data/ --fileshare --upload
```

If I run this on each machine, it will overwrite the data in the share.  I could use the `--collate` command, but that assumes my data is flat.  

So locally, on the machine, I have to first copy the files to a `machineX` directory, then call blobxfer.

I'd like to maintain the directory structure and just specify a destination directory on the share.  So adding a `--dest-dir` option or something similar would be perfect.

```
blobxfer cockroachbackup gamma data/ --fileshare --upload --dest-dir machine0
```

**Comment by alfpark** [comment]
@BramGruneir Thanks for the feedback. I'll add this to the rewrite milestone.

**Comment by alfpark** [comment]
Rolling this request into issue #24.
