### ISSUE TITLE
Can blobxfer work thru a proxy

### ISSUE THREAD

**Issue by dcrick01** [Azure/blobxfer#16]
I would like to find out if blobxfer can work via a corporate proxy.

Based our our company security setup we must do all our traffic via proxy servers with azure for all machines that are not in azure.

Thanks,
crick

**Comment by dcrick01** [comment]
I'm sorry if this is not the correct place to ask this question, but i've checked all other sites.

**Comment by alfpark** [comment]
@dcrick01 `requests` is used to perform all REST actions, so you can either `export HTTPS_PROXY=ip:port` on Linux or `set https_proxy=ip:port` on Windows to use a proxy.

**Comment by dcrick01** [comment]
That is what I’m doing:

set https_proxy=http://<ipaddr>:<port>
set HTTPS_PROXY=http://<ipaddr>:<port>

or do I need to remove the http://

Thanks,
Crick

**Comment by alfpark** [comment]
I don't think it matters, you can try removing the `http://`. Is your proxy a SOCKS proxy or a HTTP proxy?

Can you try testing through the Python repl?
```
$ export HTTP_PROXY="<ipaddr>:<port>"
$ export HTTPS_PROXY="<ipaddr>:<port>"

$ python
>>> import requests
>>> requests.get('http://bing.com')
```

**Comment by dcrick01** [comment]
Removing the http:// solved the problem.

Thanks,
crick
