### ISSUE TITLE
Upload/Download files from Azure Strorage Container using blobxfer

### ISSUE THREAD

**Issue by narendraprasath** [Azure/blobxfer#2]
Hello author,
I tried to upload some file in to azure container. I ran this command line argument in linux machine. But there was no response for a long time and it showing the same status for long time. What the issue for this? Anyone would suggest me where this is going wrong?

Uploading Command : **blobxfer accountname containername files_name --saskey "KEY"** 

This command showing as follows,
Details of the options like timeout,storage account,use SAS,container/share name, and  transfer direction, etc.,
script start time: 2016-09-14 06:57:46

But, After a long period i.e more than 2 hours also showing the same status. The file size is also less than 1Mb.  I am facing the same issue for downloading the files as well. Give me some suggestion to proceed for uploading/downloading.
Thanks in advance!!

**Comment by alfpark** [comment]
@narendraprasath what is "files_name" exactly? Is that the name of a **single** file you're trying to upload? Also, please use the `--upload` parameter.

When you CTRL+C (break) the execution of the script, can you paste the stack trace?

**Comment by alfpark** [comment]
Closing since there's been no response.
