### ISSUE TITLE
Unable to upload large files

### ISSUE THREAD

**Issue by mbettex** [Azure/blobxfer#28]
I tried to use blobxfer to upload a large file (around 264 GB) to an azure block blob storage. The tool could not upload the file. The error message was:

> RuntimeError: 63084 chunks for file my_big_file exceeds Azure Storage limits for a single block blob

I believe that this is due to the limitation on the MAX_BLOB_CHUNK_SIZE_BYTES set to 4194304 (63084 * 4194304 B = 264 GB). According to [azure documentation](https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits#storage-limits), the maximum number of blocks in a block blob is 50000 blocks of 100 MB. 63084 blocks is of course over the limit for the number of blocks and that is why it fails. But I don't understand this artificial limitation to the maximum block size of 4194304 bytes (which is 4 MB) imposed by blobxfer, which is 25 times less than the maximum in the azure documentation.

Anyway, the quick fix for me was to increase the value of MAX_BLOB_CHUNK_SIZE_BYTES to a higher value and then I could upload my file without any issue.

**Comment by alfpark** [comment]
@mbettex You are correct. The change to the maximum block size was a somewhat recent change - the old maximum was 4MiB. Glad to see that you could correct it locally to get over your issue.

This will be properly addressed in 1.0.0 (the max chunk size will be configurable).

**Comment by alfpark** [comment]
This is now fixed in 1.0.0a4. You can either let `blobxfer` automatically determine the block size or configure it yourself for uploads with `--chunk-size-bytes`.
