### ISSUE TITLE
Directory mirroring

### ISSUE THREAD

**Issue by leovin** [Azure/blobxfer#3]
Hey,

cmd: "blobxfer myStorageAcc myContainer /hamachi --upload --fileshare"

problem: on Azure there are multiple folders created instead of one:
- ham
- hama
- hamac
- hamachi

using docker, tried versions 0.11.0 - 0.11.4 on ubuntu and phusion/baseimage, playing with all cmd options available - same result

any chance there's a bug somewhere around https://github.com/Azure/blobxfer/blob/master/blobxfer.py#L2330 ?

**Comment by alfpark** [comment]
@leovin what is in the /hamachi directory you are trying to upload? Do you have those folders inside of /hamachi?

**Comment by leovin** [comment]
single folder with files, after copy files are split across the above 4 folders

**Comment by leovin** [comment]
# pwd                                                                                                                                                                    
/cs/hamachi                                                                                                                                                              
# ls                                                                                                                                                                     
h2-client.key      h2-engine.ini       h2-key-205-241-139  h2-sta-205-225-691                                                                                            
h2-engine-notice   h2-engine.ini.bak   h2-key-205-279-601  h2-sta-205-229-643                                                                                            
h2-engine.cfg      h2-engine.log       h2-server.key       h2-sta-205-241-139                                                                                            
h2-engine.cfg.bak  h2-key-199-653-833  h2-sta-199-653-833  h2-sta-205-279-601                                                                                            
h2-engine.id       h2-key-205-225-691  h2-sta-199-790-694                                                                                                                
h2-engine.id.bak   h2-key-205-229-643  h2-sta-205-225-237

**Comment by leovin** [comment]
tomorrow will try to provide exact STR for alfpark/blobxfer docker image (i.e. commands to create sample dir structure with files and upload to azure files)

**Comment by leovin** [comment]
please find below a way to reproduce
commands are executed on docker host
half of the files go to "haamaach" directory and half to "haamaachiii" ...


mkdir /longtestdirname
mkdir /longtestdirname/haamaachiii
for ((y=1; y<=100; y++)); do : echo "t" > /longtestdirname/haamaachiii/"$y"; done
for ((y=1; y<=100; y++)); do : echo "soooome teeeext$y" > /longtestdirname/haamaachiii/somereallylongfilename"$y".txt; done

docker run --rm  -v /longtestdirname/haamaachiii:/haamaachiii -t alfpark/blobxfer storageAcc container /haamaachiii --upload --strip-components=0 --no-computefilemd5 --fileshare --storageaccountkey key

**Comment by leovin** [comment]
boils down to: ("somefilename.txt" goes to "haamaach" and "1" goes to "haamaachiii")

mkdir /haamaachiii
echo "t" > /haamaachiii/1
echo "t" > /haamaachiii/somefilename.txt

docker run --rm  -v /haamaachiii:/haamaachiii -t alfpark/blobxfer storageAcc fileShare /haamaachiii --upload --strip-components=0 --fileshare --storageaccountkey key

**Comment by alfpark** [comment]
@leovin Thanks for the repro steps. Fix will be in 0.11.5 release.

**Comment by leovin** [comment]
thank you for prompt fix!

**Comment by leovin** [comment]
tested 0.11.5 - works!
thanks again and have a good day!
