### ISSUE TITLE
blobxfer - account sas token  - permission rlac

### ISSUE THREAD

**Issue by gideonrobin** [Azure/blobxfer#30]
Team,

I am just exploring blobxfer. I am able to upload and download files to/from azure blob storage using both AccessKey or SAS token.

I have a specific requirement wherein I have a SAS token which has Read-List-Create-Add permissions. 
When i tried to upload using that SAS token it fails in blobxfer. But the same works fine with Azure Storage explorer.

![azexplorer](https://cloud.githubusercontent.com/assets/23633175/25128432/5d251ef0-2457-11e7-85c5-6bfeddfc11fa.png)

![azportal](https://cloud.githubusercontent.com/assets/23633175/25128492/993fa50e-2457-11e7-812d-1fd16bf7f6fa.png)

Command Used:
blobxfer STORAGE CONTAINER FILE01 --upload --saskey  "?sv=2016-05-31&ss=b&srt=sco&sp=rlac&se=2017-04-18T14:44:55Z&st=2017-04-18T06:31:55Z&spr=https&sig=signature"
 
_HTTPError: 403 Client Error: This request is not authorized to perform this operation using this permission._ 

Please help me out!

-Robin

**Comment by alfpark** [comment]
@gideonrobin Does the blob already exist? Then Create is insufficient. You will need Write permissions.

**Comment by gideonrobin** [comment]
@alfpark The container already exists. Uploading blob for the first time. Fails with blobxfer but succeeds with Azure Storage Explorer.

**Comment by alfpark** [comment]
Are you sure it's succeeding for the first time with no pre-existing blob? Your screenshot of Azure Storage Explorer seems to suggest otherwise.

Please try adding the Write permission.

blobxfer does not do anything other than pass the SAS to Azure Blob Storage. The error being returned is from Azure Storage and not blobxfer.

**Comment by gideonrobin** [comment]
@alfpark I think there is a miss communication. Sorry, Let me make it clear. The screenshot I mentioned is from Storage Explorer - where the first upload succeeds and the second upload of same file (overwrite) fails, which is ideal as I gave only CREATE permission. 

But when I tried the same - uploading a new file using blobxfer with same SAS token it throws this error message.
HTTPError: 403 Client Error: This request is not authorized to perform this operation using this permission.

I am trying with files with size approx 10-200kb. 

Not sure if I am missing anything.

Your help will be highly appreciated. TIA.

**Comment by alfpark** [comment]
Blobxfer does not upload blobs as one operation if they are under 64MB unless the file is zero-bytes. Files with size greater than zero bytes are chunked into blocks and uploaded in parallel. From what I can gather here, it looks like block uploading requires the Write permission.

blobxfer 1.0.0a1 will include a `--no-overwrite` flag which will protect you from overwriting blobs on the remote side independent of SAS.

**Comment by gideonrobin** [comment]
@alfpark Thanks for the update. 

I am glad about the --no-overwrite flag which will be introduced.

Also it would be great if you could support the SAS token with Create permission. Because as an IT admin, if i provide SAS token with write privilege, the end user can either use use "--no-overwrite" option as an ideal way. But if he accidentally/intentionally removes that flag and do an upload, the actual data that is stored in Azure will be lost.

So I feel SAS token with Create permission will be more appropriate that will prevent accidental/intentional overwrite. Hope this will also be introduced with this GREAT utility "blobxfer"!

Many thanks
Robin.

**Comment by alfpark** [comment]
I did some more testing regarding this. Azure Storage Explorer as of version 0.8.12 arbitrarily uses a single PUT blob operation for files 32MB or less. Anything greater than this it will chunk into blocks which requires Write permission. This is less than the old 64MB max (the new max is 256MB for 2016-05-31 REST version).

I will see if I can fit in an option for a configurable "oneshot" upload up to 256MB in 1.0.0a1.

**Comment by alfpark** [comment]
This is now supported in 1.0.0a4. Please see the `--one-shot-bytes` option.

**Comment by seguler** [comment]
Hi @pratt06 

You will first need to install the beta release via ```pip install blobxfer==1.0.0b2```

Then a command like this should work:
cat test.json | blobxfer upload --storage-account myaccount--remote-path container/blob --storage-account-key ....== --local-path - --rename

@alfpark it seems the installation documents in the develop branch are not quite clear on how to install the beta version.

**Comment by pratt06** [comment]
Hi @seguler 

Thanks for pointing out, I have installed 1.0.0b2 version.

Setup:
I have set up the storage key value as environment variable 
export BLOBXFER_STORAGEACCOUNTKEY= 'key_name'

Executed command:
cat test.json | blobxfer upload --storage-account 'storage_account_name' --remote-path 'container_name/blob_name' --storage-account-key ....== --local-path - --rename

Exception occured
azure.common.AzureHttpError: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.

Can you please check?

**Comment by alfpark** [comment]
Note the environment variables have changed in 1.0.0. Try the following:

```shell
export BLOBXFER_STORAGE_ACCOUNT_KEY="mykey"
cat test.json | blobxfer upload --storage-account myaccount --remote-path container/blob --rename --local_path -
```

**Comment by pratt06** [comment]
Thanks, it worked.

**Comment by alfpark** [comment]
Thanks, fixed above.
