### ISSUE TITLE
Add possibility to copy files between containers?

### ISSUE THREAD

**Issue by code-K** [Azure/blobxfer#37]
Hi there! First of all thanks much for the great work! :) 👍 

Is there actually a possibility to copy files between two containers? For example with a source of "file share" container and destination "blob" container?

This would be really perfect!

If this currently isn't possible, is it planned?

Thanks much and best regards,
Christian

**Comment by alfpark** [comment]
In version 1.0.0, you can use the `synccopy` command to accomplish this, but the `mode` (e.g., block blob) is preserved.

Being able to copy between modes is something that would require some additional logic (unknown if this would be feasible in 1.0.0). However, you could mount your file share on your own machine (or VM) and then use blobxfer to copy it into blob storage as a workaround.

**Comment by alfpark** [comment]
I think it's possible to add cross-mode support. I'll add this to the next version.

**Comment by alfpark** [comment]
This is now supported in 1.0.0b1.
