### ISSUE TITLE
Certificate error with version of requests

### ISSUE THREAD

**Issue by sprtrox** [Azure/blobxfer#39]
By default, the version of blobxfer available via pip presented the following error, which an upgrade of requests fixed.
`AttributeError: 'X509' object has no attribute '_x509'`

Installing requests==2.18.2 from 2.12.3 remedied this issue for me.

**Comment by alfpark** [comment]
Do you encounter this issue with the 1.0.0 releases?

**Comment by sprtrox** [comment]
1.0.0a5 was fine in a cursory test, though I did have to adjust the parameters, and install dependencies of the extension modules. Updating the requests module was a sufficient workaround if updating to 1.0.0a5 isn't an option.

**Comment by alfpark** [comment]
Thanks for confirming and providing a workaround for existing users. Closing since this will be fixed in the 1.x releases.
