### ISSUE TITLE
Question on performance

### ISSUE THREAD

**Issue by leovin** [Azure/blobxfer#4]
input: 2Gb folder with 400 directories and 10k files (MD5 calculation is disabled)

problem: time to start file upload is about half an hour

is this expected? any way to speed up start of upload?

**Comment by alfpark** [comment]
@leovin I'm surprised that it would take that long for 10k files with MD5 disabled. One thing you can do is invoke blobxfer in parallel and either: (1) split your folder into multiple folders (either by hand or volume mounting them with docker) and use multiple blobxfer sessions in parallel, (2) pre-archive your folder into one or more archives - this will, in general be much faster, especially for Azure files (if that is what you're using), (3) use the `--include` parameter to partition off different parts of the folder and use multiple blobxfer sessions in parallel.

There are some fundamental design issues at play here that contribute to the overall potential slowness in start up and memory usage in the script. There are plans for a v2, but this is far in the future. Please let me know if the above workarounds accelerate your start up. Also please bear in mind that Azure files is not intended to be high performance.

**Comment by leovin** [comment]
Thank you for suggestions.

Parallelization is not an option - because backup is performed from app server and parallelization would eat up all resources. For same reason archiving is also not an option.
Of course there's an option to auto-provision separate VM, use parallelization and then kill VM, but I prefer simple solutions.
I was looking for a "free lunch" here, hoping that blobxfer does something that I don't need and disabling can speed it up (something like MD5).

Original backup strategy was to sync frequently (for replication) and then snapshot (for history).
But slow startup is less of a problem now, after I realized that Azure Files doesn't support snapshots yet :)
So I ended up with a hard compromise - full backup on a daily basis - and startup time is not an issue anymore.
Now the only concern is monthly bill for daily full copy :)

**Comment by alfpark** [comment]
@leovin Since you are presumably not using encryption, you can decrease the number of workers via `--numworkers` to each instance in parallel and still use the same overall amount of cpu. Blobxfer is completely IO-bound in the non-encryption use case.

Hope that helps. Please close the issue if you feel this has been resolved.
