### ISSUE TITLE
Increase _MAX_BLOB_CHUNK_SIZE_BYTES?

### ISSUE THREAD

**Issue by mlin** [Azure/blobxfer#40]
Hi @alfpark I'm back trying again to upload some >200GB blobs since the [size limitation was greatly increased late last year](https://azure.microsoft.com/en-us/blog/general-availability-larger-block-blobs-in-azure-storage/). As I understand that article, the maximum chunk/block size is increased from 4MB to 100MB. In blobxfer.py we still seem to have hardcoded `_MAX_BLOB_CHUNK_SIZE_BYTES = 4194304`, and the 50,000 chunk limit, so it won't initiate an upload above the old 195GB limit. Should that constant be increased?

**Comment by alfpark** [comment]
@mlin Please see [issue 28](https://github.com/Azure/blobxfer/issues/28). As per the issue resolution, you can modify the constant yourself temporarily for the time being. The path forward is to migrate to the new 1.x series of releases where this parameter can either be manually or automatically determined for you. I am nearing the release of 1.0.0b1 which you may want to begin testing your workloads against.

**Comment by mlin** [comment]
SGTM! look forward to new docker images

**Comment by alfpark** [comment]
1.0.0b1 has been released, you can test functionality with the Docker image: `alfpark/blobxfer:1.0.0b1`
