### ISSUE TITLE
blobxfer getting stuck when copying a container with millions of files

### ISSUE THREAD

**Issue by LaurenBenoit** [Azure/blobxfer#43]
I am trying to download the contents of a virtual directory on Azure storage to my local storage. The virtual directory has ~ 10M small sized blobs( < 15 KB each ). 

I am using the following commands to download the blobs

Command 1:
`blobxfer --storageaccountkey "STORAGE_KEY" MY_STORAGE_ACCOUNT MY_CONTAINER . --download --remoteresource .`

Command 2:
`blobxfer --storageaccountkey "STORAGE_KEY" MY_STORAGE_ACCOUNT MY_CONTAINER . --download --remoteresource . --include 'test/*'`

After I type in the command I get stuck at 

"attempting to copy entire container pictures to ." 

I've been stuck here for 30 mins. The same operation starts the download instantaneously while using AZcopy on ubuntu. Maybe the command is trying to compute the total number of files. If that's the case then Is there a way to skip that?

**Comment by alfpark** [comment]
Please try `1.0.0b2`.

**Comment by LaurenBenoit** [comment]
Updated: got this error on the same commands written above

Error: no such option: --storageaccountkey

**Comment by alfpark** [comment]
`1.0.0` series has a different command structure as noted [here](https://github.com/Azure/blobxfer/issues/27). Please see the [docs](https://github.com/Azure/blobxfer/tree/develop/docs).

**Comment by LaurenBenoit** [comment]
Thanks a bunch, I got it to work with version 1.0.0b2. However, there is one more issue. I am downloading around 4M tiny-sized files ~10KB and it's going to take me around 36 hrs. If the download fails midway, is there a way to resume the download from the point it got interrupted?

**Comment by alfpark** [comment]
You can do one of a few things:
1. Enable resume via `--resume-file <filename>`. I'm not sure how well this will perform for 4M files. 
2. You can use a "skip on" option to fake a resume. All of these options don't require a resume file, but requires a remote comparison so it may be slower than option 1.
    * MD5 (if you have files/blobs in Azure with MD5): `--file-md5 --skip-on-md5-match`
    * Content length: `--skip-on-filesize-match`
    * Last modified time: `--skip-on-lmt-ge`

**Comment by alfpark** [comment]
Closing as discussion has moved on from the initial issue.
