### ISSUE TITLE
Installing from PIP yields blobxfer-0.12.1

### ISSUE THREAD

**Issue by markmassad** [Azure/blobxfer#52]
Documentation indicates PIP will install:  blobxfer 1.0.0rc2

Not clear on how to upgrade?

**Comment by alfpark** [comment]
Can you point to the documentation that states this?

**Comment by markmassad** [comment]
https://github.com/Azure/blobxfer/releases

1.0.0rc2 
This release is a Release Candidate.
Note: **blobxfer 1.0.0rc2 is the new default install option with pip along** with the default latest Docker image.

**Comment by markmassad** [comment]
Is there any performance comparison between Azcopy and blobxfr on Linux copying from one azure storage account to another?  My test results show significant differences between the two.  Aren't they both async network copies over azure backbone between storage accounts?

**Comment by alfpark** [comment]
This is correct - I'm confused by the title of your post. When you execute `pip install blobxfer` or `pip3 install blobxfer`, do you get 0.12.1?
