### ISSUE TITLE
[Feature request] To download remote files into local without keeping the same virtual path of remote files but only file names

### ISSUE THREAD

**Issue by yokawasa** [Azure/blobxfer#66]
REQUEST:  to be able to download remote files into local without keeping the same virtual path of remote files but only file names

Here is a simple example:
```
<MyBlobStorage>: <MyContainer>/<SubDirectory1>/<SubDirectory2>/TargetFile.txt
<MyLocalVM>:/tmp
```

Suppose I want to download TargetFile.txt in blob storage to /tmp in my local VM, I run blobxfer by specifying remote path and local path with --remote-path and --local-path respectively like this:
```
blobxfer download --remote-path <MyContainer>/<SubDirectory1>/<SubDirectory2> --local-path /tmp ...
```
Then, blobxfer will attempt to download TargetFile.txt in blob storage to local VM with including path, keeping the same virtual file path like this:
```
<MyLocalVM>:/tmp/<SubDirectory1>/<SubDirectory2>/TargetFile.txt
```
But what I would like to achieve is simply to download files to local directory without keeping virtual path (virtual sub directory) like this:
```
<MyLocalVM>:/tmp/TargetFile.txt
```

Giving another example, 
Suppose I have the following 3 files in my Azure blob storage,
```
<MyBlobStorage>: <MyContainer>/<SubDirectory1>/<SubDirectory2>/TargetFile1.txt
<MyBlobStorage>: <MyContainer>/<SubDirectory1>/TargetFile2.txt
<MyBlobStorage>: <MyContainer>/TargetFile3.txt
```
I try to download the files above to my local VM /tmp directory by running the following command:
```
blobxfer download --remote-path <MyContainer> --local-path /tmp 
```
I would like to download files to local directory like this:
```
<MyLocalVM>$ ls -1  /tmp
TargetFile1.txt
TargetFile2.txt
TargetFile3.txt
```

**Comment by alfpark** [comment]
This is by design. What is the correct behavior if there are identical files in the virtual subdirectories? I'd rather not have `blobxfer` arbitrarily choose.

You can accomplish this by running a `find <args> -print0 | xargs -0 mv -t <args>` after you run `blobxfer`.

**Comment by yokawasa** [comment]
@alfpark thank you for the comment

I didn't include very important item in my request: 
- Only download 'newly added or updated blobs' in order to keep number of downloading blob files as minimum as possible

This above can be achieved by giving parameters like`--skip-on-lmt-ge`, `--skip-on-filesize-match` to blobxfer. This is why I though it good to have the feature in blobxfer. 

Do you have any idea to achieve both (1) download remote files without including virtual path (which can be achieve by your suggested command) and (2) download 'newly added or updated blobs'  at the same time?

**Comment by alfpark** [comment]
You can create symlinks to the files instead of using `mv`.

I don't want to add a feature like this into `blobxfer` because of the problem I initially outlined. Parameters that provide skip-on make this problem even more acute when combined with identically named files within subdirectories.

**Comment by MJZawacki** [comment]
I think @yokawasa's first example mimics standard copy behavior and should be implemented. In that case, the `--remote-path` would set the root directory of the download command and all sub directories under the root would be maintained (if recursive download).

Agreed that second example is dangerous for the reasons you outlined.
