### ISSUE TITLE
[Feature request]  To download remote files under specific virtual directory or container

### ISSUE THREAD

**Issue by yokawasa** [Azure/blobxfer#67]
Suppose I specify "CONTAINER_NAME/DIR1" for `--remote-path` param in download remote blob files, blobxfer dowlonads remote files with prefix matching like this:

```
---remote-path "CONTAINER_NAME/DIR1"
blobxfer does prefix matching with “CONTAINER_NAME/DIR1”, then give the following blobs as its result:
CONTAINER_NAME/DIR1/*   CONTAINER_NAME/DIR10/*   CONTAINER_NAME/DIR15/*, ….
```

My request is to be able to download remote files under specific virtual directory or container. For example, if I give "`mycontainer/foo`" to `--remote-path` param in downloading remote blobs files, I expect blobxfer to download either
-  blob files under `mycontainer/foo` virtual directory if foo is virtual directory
-  or blob file, `mycontainer/foo` if mycontainer/foo is an blob file

**Comment by alfpark** [comment]
This is due to the use internally of pathlib on remote paths.

You can just use a `--include <vdirpath>` filter, e.g., `--include dir1/*`

**Comment by yokawasa** [comment]
@alfpark  Thank you so much!
