### ISSUE TITLE
The upload logs are not listed on the terminal

### ISSUE THREAD

**Issue by SharmaHitesh** [Azure/blobxfer#71]
It is not an issue, but I am not sure how to reach out for help.

in the earlier version, I could see the process logs on the terminal when I could see which files it is skipping and which one being transferred. But in the newer version, I do not see all that on the terminal. All it shows is how many files and data being transferred.

**Comment by SharmaHitesh** [comment]
Thank you @alfpark for the response, but somehow, I am not getting the logs of what gets transferred as well. I am running command as 
`blobxfer upload --storage-account myStorageAc --remote-path blob --local-path blob --delete`

The transfer does happen, but it does not list which files are being uploaded, which gets deleted. I am running version 1.1.1

**Comment by alfpark** [comment]
Logs are output to stderr; you'll need to redirect.

**Comment by alfpark** [comment]
Also please see the `--log-file` option.

**Comment by alfpark** [comment]
Closing, please re-open if your issue is not solved.
