### ISSUE TITLE
No mention of problematic block blob name when an exception occurs

### ISSUE THREAD

**Issue by rnsc** [Azure/blobxfer#73]
Hello,

I encountered an error with the latest version of blobxfer.
Unfortunately, I don't know which block blob has caused the issue because it's not in the verbose log.
Is there any way to add the name of the blob in question when this happen ?
The source blob is rather large and the destination also, so I do not know what exact file is causing the issue.
It happened during a synccopy.

Command executed
> blobxfer synccopy -v --config blobxfer_config.yaml

Parameters:
> ============================================
>          Azure blobxfer parameters
> ============================================
>          blobxfer version: 1.2.1
>                  platform: Linux-4.13.0-1018-azure-x86_64-with-Ubuntu-16.04-xenial
>                components: CPython=2.7.12-64bit azstor.blob=1.1.0 azstor.file=1.1.0 crypt=2.2.2 req=2.18.4
>        transfer direction: Azure -> Azure
>                   workers: disk=0 xfer=64 md5=0 crypto=0
>                  log file: None
>               resume file: /tmp/blobxfer_resume.db
>                   timeout: connect=3.1 read=12.1
>               source mode: StorageModes.Auto
>                 dest mode: StorageModes.Auto
>                   skip on: fs_match=True lmt_ge=False md5=False
>         delete extraneous: True
>                 overwrite: True
>                 recursive: True
>             rename single: False
>               access tier: None
> ============================================
> 

config:
> synccopy:
>   - source:
>       - *REDACTED*: files
>     destination:
>       - *REDACTED*: files
>     options:
>       mode: auto
>       dest_mode: auto
>       access_tier: null
>       delete_extraneous_destination: true
>       overwrite: true
>       recursive: true
>       rename: false
>       skip_on:
>         filesize_match: true
>         lmt_ge: false
>         md5_match: false

Error:
> 2018-05-24 10:11:33,719 ERROR blobxfer.operations.synccopy:start:866 UnicodeDecodeError: utf8
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/blobxfer/operations/synccopy.py", line 859, in start
>     self._run()
>   File "/usr/local/lib/python2.7/dist-packages/blobxfer/operations/synccopy.py", line 801, in _run
>     self._add_to_transfer_queue(src_ase, dst_ase)
>   File "/usr/local/lib/python2.7/dist-packages/blobxfer/operations/synccopy.py", line 241, in _add_to_transfer_queue
>     src_ase)
>   File "/usr/local/lib/python2.7/dist-packages/blobxfer/operations/azure/blob/block.py", line 176, in get_committed_block_list
>     timeout=timeout).committed_blocks
>   File "/usr/local/lib/python2.7/dist-packages/azure/storage/blob/blockblobservice.py", line 312, in get_block_list
>     return self._perform_request(request, _convert_xml_to_block_list)
>   File "/usr/local/lib/python2.7/dist-packages/azure/storage/common/storageclient.py", line 354, in _perform_request
>     raise ex
> AzureException: UnicodeDecodeError: utf8
> Traceback (most recent call last):
>   File "/usr/local/bin/blobxfer", line 11, in <module>
>     sys.exit(cli())
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 64, in new_func
>     return ctx.invoke(f, obj, *args[1:], **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/blobxfer_cli/cli.py", line 977, in synccopy
>     ctx.general_options, ctx.credentials, spec
>   File "/usr/local/lib/python2.7/dist-packages/blobxfer/operations/synccopy.py", line 859, in start
>     self._run()
>   File "/usr/local/lib/python2.7/dist-packages/blobxfer/operations/synccopy.py", line 801, in _run
>     self._add_to_transfer_queue(src_ase, dst_ase)
>   File "/usr/local/lib/python2.7/dist-packages/blobxfer/operations/synccopy.py", line 241, in _add_to_transfer_queue
>     src_ase)
>   File "/usr/local/lib/python2.7/dist-packages/blobxfer/operations/azure/blob/block.py", line 176, in get_committed_block_list
>     timeout=timeout).committed_blocks
>   File "/usr/local/lib/python2.7/dist-packages/azure/storage/blob/blockblobservice.py", line 312, in get_block_list
>     return self._perform_request(request, _convert_xml_to_block_list)
>   File "/usr/local/lib/python2.7/dist-packages/azure/storage/common/storageclient.py", line 354, in _perform_request
>     raise ex
> azure.common.AzureException: UnicodeDecodeError: utf8

**Comment by alfpark** [comment]
Please see this [issue](https://github.com/Azure/blobxfer/issues/64).

You can deduce which file is having this issue by issuing the parameter: `--enable-azure-storage-logger`

**Comment by alfpark** [comment]
Closing, please re-open if your issue has not been addressed.
