### ISSUE TITLE
 blobxfer upload --delete Delete extraneous directory on target

### ISSUE THREAD

**Issue by olblak** [Azure/blobxfer#78]
#### Expected Results
I would expect directory to be delete as well like files

**Comment by alfpark** [comment]
If the directory is empty, this is a [known limitation](https://github.com/Azure/blobxfer/blob/master/docs/99-current-limitations.md#azure-file-limitations) for Azure Files when using `--delete`.

**Comment by olblak** [comment]
Thanks for the information
