### ISSUE TITLE
Accept entire URLs (instead of components) in the CLI

### ISSUE THREAD

**Issue by alfpark** [Azure/blobxfer#79]
#### Feature Request Description
Currently, SAS tokens are supported, but must be explicitly broken apart from a URL. Accept a full URLs for all modes instead of having to specify the individual components of the URL for convenience.

#### Describe Preferred Solution
* Parameter and env var for upload/download and a separate one for sync copy

This will be a CLI only option, there will be no corollary for YAML configuration due to how the referencing works.

**Comment by ckcollab** [comment]
I am running into confusion with this right now, not really sure how to properly pass the URL to `blobxfer` and how to properly pass the bucket name + file path I want to upload to.

**Comment by ckcollab** [comment]
Wahoo! Thanks @alfpark :)
