### ISSUE TITLE
Feedback Request

### ISSUE THREAD

**Issue by alfpark** [Azure/blobxfer#8]
Hello blobxfer users,

I would like to solicit feedback on what you feel is missing or what you would like to see improved in the next version of blobxfer. The next version of blobxfer will be a nearly from scratch rewrite incorporating collected feedback over the past year. Some ideas include:
- Restrict to Python 3.4/3.5 for native asyncio (docker image would still be available for those stuck on Python 2.7 or earlier versions of Python 3.x)
- ~~Rewrite in Go~~
- Please see other ideas which have been promoted from thoughts to "maybes" in the associated kanban board: https://github.com/Azure/blobxfer/projects/1

Thanks!

**Comment by mrm** [comment]
Hi alfpark,

It would be great if you could stream data using blobxfer. For example I'd like to stream a large file that's being generated directly to Azure Storage. As the resulting file is larger than my disk space I can't store it locally first. 

```sh
$ generate_large_file.sh | blobxfer myst largefiles - --upload --remoteresource large_file.tar.gz
```

Something like passing a `-` as the localresource would be great or even just `/dev/stdin`. Currently the size is calculated before actually sending it, which in the case of `/dev/stdin` is 0 resulting in an empty file being uploaded.

**Comment by alfpark** [comment]
@mrm Thanks for the suggestion. I think this scenario can work with append blobs which have been considered for support. Will your workload work with append blobs?

**Comment by polarapfel** [comment]
I second mrm's request. Common scenario:

Uploading files as block blobs where the local file size exceeds the limit of a valid block blob on Azure (~195MB). In that case, before uploading, the file needs to be split, for example using SPLIT(1). I don't want to do this on disk locally. I want to pipe the output from split directly to blobxfer, so I don't need to write it to my local disk in the first place.

Also, please consider adding a proper manpage for Unix hosts with some example calls (like the problem described above).

Thanks!

Tobias W.

**Comment by alfpark** [comment]
@polarapfel Thanks for the scenario. I will move append blob support to committed.

**Comment by mark-sp** [comment]
Hi alfpark,

We recently switched from IBM's Softlayer to Azure as mirror for the local storage, and it looks that your tool would fit perfectly to sync both locations.

Nevertheless, I am missing an important functionality: we've got very big files that are never modified, so there is no need to recalculate MD5 on each run, however, using the option --no-computefilemd5 automatically re-uploads the file, so at the end the cure may be worst than the disease. 

Is there any way to switch off the md5 calculating and avoid uploading the file if a file with the same name already exists in the remote location? I am not using --upload option, it was already my first though

**Comment by alfpark** [comment]
@mark-sp Unfortunately there's no way to do this currently. However, a crude workaround is to use an include filter which only includes the files that you wish to upload.

I'll move diff on LMT to committed which would be a solution for your case. I'll also consider adding a no clobber that works on upload.

**Comment by alfpark** [comment]
Thanks for the feedback. The feedback comments period is now closed and action has begun on the rewrite.
