### ISSUE TITLE
Azure Data Lake

### ISSUE THREAD

**Issue by tudormaz** [Azure/blobxfer#90]
Hello. Is it possible to transfer data from Azure Data Lake to a Storage Account? If so, how?
I currently am receiving an error when trying to download from it. 
blobxfer download --storage-url https://mydatalake.azuredatalakestore.net/my-project/my-file.csv --local-path /persistence --sas '\<my-token\>'
`ValueError: Invalid derived mode from --storage-url: azuredatalakestore`

**Comment by alfpark** [comment]
Azure Data Lake Gen1 accounts are not supported (and will not be supported). You can use blobxfer on ADLS Gen2 accounts to access data through the `blob` endpoint. Direct access to the `dfs` endpoint is not supported at this time.
