### ISSUE TITLE
blobxfer exceptions do not terminate with non-zero exit code

### ISSUE THREAD

**Issue by dommorin** [Azure/blobxfer#96]
#### Azure blobxfer parameters output
> blobxfer download --storage-account <valid_storage_account> --local-path <drive_with_no_free_space> --progress-bar --log-file <valid_log_file> --remote-path <valid_blob_path>
============================================
         Azure blobxfer parameters
============================================
         blobxfer version: 1.5.5
                 platform: Windows-10-10.0.17763-SP0
               components: CPython=3.7.2-64bit azstor.blob=1.4.0 azstor.file=1.4.0 crypt=2.4.2 req=2.20.1
       transfer direction: Azure -> local
                  workers: disk=27 xfer=18 md5=0 crypto=0
                 log file: C:\\Users\\domorin\\AppData\\Local\\Temp\\tmps4uchhwk
                  dry run: False
              resume file: None
                  timeout: connect=10 read=200 max_retries=1000
                     mode: StorageModes.Auto
                  skip on: fs_match=False lmt_ge=False md5=False
        delete extraneous: False
                overwrite: True
                recursive: True
            rename single: False
         chunk size bytes: 0
         strip components: 0
         compute file md5: False
       restore properties: attr=False lmt=False
          rsa private key: None
        local destination: c:\\Temp\\mount
download progress: [                              ] 0.00%        0.000 MiB/sec, 0/1 downloaded'

#### Steps to Reproduce
blobxfer download --storage-account <valid_storage_account> --local-path <drive_with_no_free_space> --progress-bar --log-file <valid_log_file> --remote-path <valid_blob_path>

#### Expected Results
blobxfer should return a proper error code

#### Actual Results
blobxfer returns 0 but destination remains empty (no disk space)

#### Additonal Comments
As a workaround, when destination is empty, I compare the disk space available with the size of the blob using azure block blob service library to raise the proper exception.

**Comment by alfpark** [comment]
Exceptions are logged, but do not terminate the program with non-zero exit code.
